spring:
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=true&serverTimezone=GMT&useUnicode=true&characterEncoding=utf8


    username: root
    password: 1724
    # 模板编码
  thymeleaf:
    encoding: UTF-8
    #日志
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.lrm: info
#  file:
#    path: log/blog-dev.log
